### ISSUE TITLE
Garde-fou sur les doublons

### ISSUE THREAD

**Issue by sebez** [klee-contrib/topmodel#67]
# Contexte

```
class:
  trigram: TOD
  name: TurnoverDeclaration
  comment: Turnover Declaration item.
  properties:
    - name: ShopId
      label: ShopId
      domain: DO_ID
      comment: Shop ID for declaration.
      required: true

    - association: Shop
      label: Shop
      required: true
      comment: Shop.
```

Dans une classe, je me trompe et je modélise à la fois un `ShopId` à la main et via une association à `Shop`.

# Constaté

Erreur dégueulasse :

```
ModelStore -------- Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at TopModel.Core.ModelStore.ResolveReferences(ModelFile modelFile)+MoveNext() in /home/runner/work/topmodel/topmodel/TopModel.Core/ModelStore.cs:line 389
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at TopModel.Core.ModelStore.TryApplyUpdates() in /home/runner/work/topmodel/topmodel/TopModel.Core/ModelStore.cs:line 130
```

# Attendu

J'aimerais bien qu'un garde-fou me pointe mon erreur gentiment.

`wesh gros arrête de coder avec les genoux, l'attribut ShopId est défini en double sur l'entité TurnoverCollection`.

**Comment by sebez** [comment]
Ce serait quand même mieux que l'IDE me fasse un feedback en temps réel.

**Comment by JabX** [comment]
Si on met en place une vraie erreur, elle remontera dans l'IDE automatiquement :)

**Comment by JabX** [comment]
De ce que j'ai compris, l'erreur mise en place par @gideruette ne fonctionne pas dans tous les cas. Peut-on le reproduire ?
